DROP TABLE IF EXISTS repas;
CREATE TABLE repas(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT NOT NULL,
    description TEXT NOT NULL,
    prix REAL NOT NULL,
    categorie BOOLEAN NOT NULL,
    statut TEXT NOT NULL DEFAULT disponible,
    quantite INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
